server:
  port: 9000

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service:8761/eureka
#

#axon:
#  axonserver:
#    servers: ${AXONSERVER_HOST:axonserver}

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/auth/**
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
        - id: usersservice
          uri: lb://usersservice
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter
        - id: persionalinforservice
          uri: lb://personalinfoservice
          predicates:
            - Path=/personalInfo/**
          filters:
            - AuthenticationFilter
