server:
  port: 9000

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service:8761/eureka
#

#axon:
#  axonserver:
#    servers: ${AXONSERVER_HOST:axonserver}

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: userServiceAuth
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
        - id: userServiceCommand
          uri: http://localhost:8080
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
        - id: userServiceQuery
          uri: http://localhost:8080
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: personalInformService
          uri: lb://personalinfoservice
          predicates:
            - Path=/personalInfo/**
          filters:
            - AuthenticationFilter
